name: multiselect_field
description: "A flexible dropdown field supporting single/multiple selection modes, styles, titles, etc"
version: 1.6.8
homepage: https://github.com/JhonaCodes/multiselect_field.git

environment:
  sdk: ^3.9.0


dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  alchemist: ^0.12.1
  lints: ^6.0.0

flutter:
  uses-material-design: true
