name: multiselect_field
description: "A flexible dropdown field supporting single/multiple selection modes, styles, titles, etc"
version: 1.5.4
homepage: https://github.com/JhonaCodes/multiselect_field.git

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  alchemist: ^0.11.0
  lints: ^5.0.0

flutter:
  uses-material-design: true
